
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq
  labels:
    app: vpromq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpromq
  template:
    metadata:
      labels:
        app: vpromq
    spec:
      containers:
        - name: vpromq
          image: rabbitmq
          ports:
            - name: vpromq-port
              containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rmq-pass
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"